# Generated by Django 6.0 on 2026-01-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_lead_source_lead_raw_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='capacity_kl',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='raw_capacity',
        ),
        migrations.AddField(
            model_name='lead',
            name='capacity',
            field=models.CharField(blank=True, help_text='Raw capacity input exactly as entered by the user', max_length=100, null=True),
        ),
    ]
